theme: minima
title: My Thoughts on "Paper"
description: Engineering, data systems, and AI workflows.
url: "https://thomasyu888.github.io"

author: Tom Yu
github_username: thomasyu888

plugins:
  - jekyll-feed
